In [261]:
import pandas as pd
import numpy as np

In [262]:
weather2023 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 0)
weather2022 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 1)
weather2021 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 2)
weather2019 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 3)
weather2018 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 4)
weather2017 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 5)
weather2016 = pd.read_excel('./Weather data_v1.xlsx',sheet_name = 6)

In [241]:
weather2023 = weather2023.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2022 = weather2022.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2021 = weather2021.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2019 = weather2019.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2018 = weather2018.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2017 = weather2017.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()
weather2016 = weather2016.drop(labels = 1,axis = 0).drop(labels = ['Unnamed: 1'],axis = 1).reset_index()

In [242]:
weather2023[['Date','Year']] = [pd.Timestamp('2023-04-23'),'2023']
weather2022[['Date','Year']] = [pd.Timestamp('2022-04-24'),'2022']
weather2021[['Date','Year']] = [pd.Timestamp('2021-09-12'),'2021']
weather2019[['Date','Year']] = [pd.Timestamp('2019-04-28'),'2019']
weather2018[['Date','Year']] = [pd.Timestamp('2018-04-29'),'2018']
weather2017[['Date','Year']] = [pd.Timestamp('2017-04-23'),'2017']
weather2016[['Date','Year']] = [pd.Timestamp('2016-04-17'),'2016']

In [243]:
weather2023.head(5)

,index,Uhrzeit,Temp,Wetter,Wind,Luftfeuchte,Barometer,Date,Year
0,0,00:20:00,15 °C,Leichter Regen. Heiter.,4 km/h,0.82,1006 hPa,2023-04-23,2023
1,2,00:50:00,15 °C,Leichter Regen. Heiter.,6 km/h,0.82,1006 hPa,2023-04-23,2023
2,3,01:20:00,14 °C,Vorüberziehende Wolken.,4 km/h,0.88,1005 hPa,2023-04-23,2023
3,4,02:50:00,14 °C,Leichter Regen. Vorüberziehende Wolken.,11 km/h,0.88,1005 hPa,2023-04-23,2023
4,5,03:20:00,13 °C,Vorüberziehende Wolken.,9 km/h,0.94,1005 hPa,2023-04-23,2023

In [244]:
all_weathers = pd.concat([weather2023,
                              weather2022,
                              weather2021,
                              weather2019,
                              weather2018,
                              weather2017,
                              weather2016],ignore_index = True)

In [245]:
all_weathers.count()

index          315
Uhrzeit        315
Temp           315
Wetter         315
Wind           315
Luftfeuchte    315
Barometer      315
Date           315
Year           315
dtype: int64

In [246]:
all_weathers.head()

,index,Uhrzeit,Temp,Wetter,Wind,Luftfeuchte,Barometer,Date,Year
0,0,00:20:00,15 °C,Leichter Regen. Heiter.,4 km/h,0.82,1006 hPa,2023-04-23,2023
1,2,00:50:00,15 °C,Leichter Regen. Heiter.,6 km/h,0.82,1006 hPa,2023-04-23,2023
2,3,01:20:00,14 °C,Vorüberziehende Wolken.,4 km/h,0.88,1005 hPa,2023-04-23,2023
3,4,02:50:00,14 °C,Leichter Regen. Vorüberziehende Wolken.,11 km/h,0.88,1005 hPa,2023-04-23,2023
4,5,03:20:00,13 °C,Vorüberziehende Wolken.,9 km/h,0.94,1005 hPa,2023-04-23,2023

In [247]:
cols = ['Temp','Wind','Barometer']
all_weathers[cols] = all_weathers[cols].replace('\D','',regex = True)
all_weathers[cols] = all_weathers[cols].apply(pd.to_numeric)

In [248]:
all_weathers.head()

,index,Uhrzeit,Temp,Wetter,Wind,Luftfeuchte,Barometer,Date,Year
0,0,00:20:00,15,Leichter Regen. Heiter.,4.0,0.82,1006,2023-04-23,2023
1,2,00:50:00,15,Leichter Regen. Heiter.,6.0,0.82,1006,2023-04-23,2023
2,3,01:20:00,14,Vorüberziehende Wolken.,4.0,0.88,1005,2023-04-23,2023
3,4,02:50:00,14,Leichter Regen. Vorüberziehende Wolken.,11.0,0.88,1005,2023-04-23,2023
4,5,03:20:00,13,Vorüberziehende Wolken.,9.0,0.94,1005,2023-04-23,2023

In [249]:
all_weathers.dtypes

index                   int64
Uhrzeit                object
Temp                    int64
Wetter                 object
Wind                  float64
Luftfeuchte           float64
Barometer               int64
Date           datetime64[ns]
Year                   object
dtype: object

In [250]:
all_weathers['Date_Uhrzeit'] = all_weathers['Date'].astype(str) + ',' + all_weathers['Uhrzeit'].astype(str)

In [251]:
all_weathers['Date_Uhrzeit'] = pd.to_datetime(all_weathers['Date_Uhrzeit'],format = "%Y-%m-%d,%H:%M:%S")

In [252]:
all_weathers.head()

,index,Uhrzeit,Temp,Wetter,Wind,Luftfeuchte,Barometer,Date,Year,Date_Uhrzeit
0,0,00:20:00,15,Leichter Regen. Heiter.,4.0,0.82,1006,2023-04-23,2023,2023-04-23 00:20:00
1,2,00:50:00,15,Leichter Regen. Heiter.,6.0,0.82,1006,2023-04-23,2023,2023-04-23 00:50:00
2,3,01:20:00,14,Vorüberziehende Wolken.,4.0,0.88,1005,2023-04-23,2023,2023-04-23 01:20:00
3,4,02:50:00,14,Leichter Regen. Vorüberziehende Wolken.,11.0,0.88,1005,2023-04-23,2023,2023-04-23 02:50:00
4,5,03:20:00,13,Vorüberziehende Wolken.,9.0,0.94,1005,2023-04-23,2023,2023-04-23 03:20:00

In [253]:
all_weathers.rename(columns = {'Temp':'Temp_Celcius','Wind':'Wind_kmperhour','Barometer':'Barometer_hPa'},inplace = True)

In [254]:
all_weathers.head()

,index,Uhrzeit,Temp_Celcius,Wetter,Wind_kmperhour,Luftfeuchte,Barometer_hPa,Date,Year,Date_Uhrzeit
0,0,00:20:00,15,Leichter Regen. Heiter.,4.0,0.82,1006,2023-04-23,2023,2023-04-23 00:20:00
1,2,00:50:00,15,Leichter Regen. Heiter.,6.0,0.82,1006,2023-04-23,2023,2023-04-23 00:50:00
2,3,01:20:00,14,Vorüberziehende Wolken.,4.0,0.88,1005,2023-04-23,2023,2023-04-23 01:20:00
3,4,02:50:00,14,Leichter Regen. Vorüberziehende Wolken.,11.0,0.88,1005,2023-04-23,2023,2023-04-23 02:50:00
4,5,03:20:00,13,Vorüberziehende Wolken.,9.0,0.94,1005,2023-04-23,2023,2023-04-23 03:20:00

In [257]:
cols = ['Year','Date','Uhrzeit','Date_Uhrzeit','Wetter','Temp_Celcius','Wind_kmperhour','Luftfeuchte','Barometer_hPa']
all_weathers = all_weathers[cols]

In [259]:
all_weathers.head()

,Year,Date,Uhrzeit,Date_Uhrzeit,Wetter,Temp_Celcius,Wind_kmperhour,Luftfeuchte,Barometer_hPa
0,2023,2023-04-23,00:20:00,2023-04-23 00:20:00,Leichter Regen. Heiter.,15,4.0,0.82,1006
1,2023,2023-04-23,00:50:00,2023-04-23 00:50:00,Leichter Regen. Heiter.,15,6.0,0.82,1006
2,2023,2023-04-23,01:20:00,2023-04-23 01:20:00,Vorüberziehende Wolken.,14,4.0,0.88,1005
3,2023,2023-04-23,02:50:00,2023-04-23 02:50:00,Leichter Regen. Vorüberziehende Wolken.,14,11.0,0.88,1005
4,2023,2023-04-23,03:20:00,2023-04-23 03:20:00,Vorüberziehende Wolken.,13,9.0,0.94,1005

In [260]:
all_weathers.to_csv('weatherdata_2023_2016.csv',index = False)